apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  labels:
    name: nginx-service
    app: php-website

spec:
  ports:
    - port: 80
      targetPort: 80
  selector:
    name: nginx-pod
    app: php-website