apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod
  labels:
    name: nginx-pod
    app: php-website

spec:
  containers:
  - name: nginx
    image: nginx:alpine
    ports:
      - containerPort: 80