apiVersion: v1
kind: Service
metadata:
  name: php-service
  labels:
    name: php-service
    app: php-website

spec:
  type: LoadBalancer
  ports:
    - port: 70
      targetPort: 70
  selector:
    name: php-pod
    app: php-website