apiVersion: v1
kind: Service
metadata:
  name: php-service
  labels:
    name: php-service
    app: php-website

spec:
  type: LoadBalancer
  ports:
    - port: 3000
      targetPort: 3000
  selector:
    name: php-pod
    app: php-website
